"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import environ
from pathlib import Path

from core.app_settings import AppConfig
from core.utils.env import populate_secure_secret

# ─────────────────────────────────────────────────────────| Environment/App |──
# Helper accessor
_env = environ.Env()

# Application base path.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load env vars
environ.Env.read_env(BASE_DIR / ".env")

# Load app settings
app_config: AppConfig = AppConfig.initialise(BASE_DIR / "settings.ini", _env)


# ────────────────────────────────────────────────────────────────| Security |──
#          See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/
SECRET_KEY = _env("SECRET_KEY")

if SECRET_KEY == "your-secret-key-here":
    populate_secure_secret(BASE_DIR)


DEBUG = _env.bool("DEBUG", default=False)

ALLOWED_HOSTS = _env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])

# ─────────────────────────────────────────────────────────────| Application |──

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 3rd Party packages
    *(["mozilla_django_oidc"] if app_config.oidc_enabled else []),
    *(["django_browser_reload", "django_watchfiles"] if DEBUG else []),
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # 3rd Party packages
    *(
        ["mozilla_django_oidc.middleware.SessionRefresh"]
        if app_config.oidc_enabled
        else []
    ),
    *(
        ["django_browser_reload.middleware.BrowserReloadMiddleware"]
        if DEBUG
        else []
    ),
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# ────────────────────────────────────────────────────────────────| Database |──
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / _env("DB_NAME", default="db.sqlite3"),
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ─────────────────────────────────────────────────────| Password validation |──
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

_pv = "django.contrib.auth.password_validation"
_django_validators = [
    {"NAME": f"{_pv}.{cls}"}
    for cls in [
        "UserAttributeSimilarityValidator",
        "MinimumLengthValidator",
        "CommonPasswordValidator",
        "NumericPasswordValidator",
    ]
]
_custom_validators: list[dict[str, str]] = []

AUTH_PASSWORD_VALIDATORS = _django_validators + _custom_validators

# ────────────────────────────────────────────────────| Internationalisation |──
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# ──────────────────────────────────| Static files (CSS, JavaScript, Images) |──
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = _env("STATIC_URL", default="static/")
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
