"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from core.app_settings import AppConfig, AppEnv

# ─────────────────────────────────────────────────────────| Environment/App |──
# Application base path.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load app environment variables
app_env: AppEnv = AppEnv.initialise(BASE_DIR / ".env")

# Load app settings
app_config: AppConfig = AppConfig.initialise(BASE_DIR / "settings.ini")


# ────────────────────────────────────────────────────────────────| Security |──
#          See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/
SECRET_KEY = app_env.secret_key

DEBUG = app_env.debug

ALLOWED_HOSTS = app_env.allowed_hosts

# Trusts X-Forwarded-Proto/Host from the reverse proxy in front of gunicorn
# (see nginx.conf) so request.is_secure() and build_absolute_uri() - which
# the OIDC redirect_uri depends on - report https correctly when TLS is
# terminated upstream. Only safe because that proxy is the sole ingress:
# the app container isn't published to the host directly (see
# docker-compose.yml), so nothing else can reach it to spoof this header.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

# ─────────────────────────────────────────────────────────────| Application |──

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 3rd Party packages
    *(["mozilla_django_oidc"] if app_config.oidc_enabled else []),
    *(["django_browser_reload", "django_watchfiles"] if DEBUG else []),
    # base app
    "tracker",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # 3rd Party packages
    *(
        ["mozilla_django_oidc.middleware.SessionRefresh"]
        if app_config.oidc_enabled
        else []
    ),
    *(
        ["django_browser_reload.middleware.BrowserReloadMiddleware"]
        if DEBUG
        else []
    ),
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # base app: Injects APP_NAME and OIDC_ENABLED into every
                # template context
                "tracker.context_processors.app_settings",
                # base app: Injects the resolved sidebar nav link list
                "tracker.context_processors.nav_links",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# ────────────────────────────────────────────────────────────────| Database |──
#              See https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": (Path(app_env.db_dir) if app_env.db_dir else BASE_DIR)
        / app_env.db_name,
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ─────────────────────────────────────────────────────| Password validation |──
# See
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

_pv = "django.contrib.auth.password_validation"
_django_validators = [
    {"NAME": f"{_pv}.{cls}"}
    for cls in [
        "UserAttributeSimilarityValidator",
        "MinimumLengthValidator",
        "CommonPasswordValidator",
        "NumericPasswordValidator",
    ]
]
_custom_validators: list[dict[str, str]] = []

AUTH_PASSWORD_VALIDATORS = _django_validators + _custom_validators

# ────────────────────────────────────────────────────| Internationalisation |──
#                         See https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-gb"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# ──────────────────────────────────| Static files (CSS, JavaScript, Images) |──
#                  See https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = app_env.static_url
STATIC_ROOT = BASE_DIR / "staticfiles"
# static/build (pnpm build's compiled output) and static/images (checked-in
# icons/logos) are servable. static/src is Tailwind CLI *input* - its raw
# `@import "tailwindcss" source(...)` directive isn't a real
# browser-resolvable path, so collectstatic's post-processor chokes on it
# if this points at the whole static/ dir.
#
# static/build only exists while there's a compiled-CSS source to collect
# from (local dev after `pnpm build`, or the Docker build stage that runs
# collectstatic). It's gitignored and deliberately excluded from the prod
# image (see .dockerignore) since collectstatic has already baked its
# contents into STATIC_ROOT by then - nothing at runtime reads from it
# again, so there's nothing to point STATICFILES_DIRS at.
_static_build_dir = BASE_DIR / "static" / "build"
_static_images_dir = BASE_DIR / "static" / "images"
STATICFILES_DIRS = [
    d for d in (_static_build_dir, _static_images_dir) if d.is_dir()
]
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# ────────────────────────────────────────────────────────| Auth / redirects |──

AUTH_USER_MODEL = "tracker.Employee"

LOGIN_URL = "/login"
LOGIN_REDIRECT_URL = "/dashboard"
LOGOUT_REDIRECT_URL = "/login"

AUTHENTICATION_BACKENDS = [
    *(
        ["tracker.auth_backend.RetainerOIDCBackend"]
        if app_config.oidc_enabled
        else []
    ),
    "core.backends.SuperuserOnlyModelBackend",
]

# ──────────────────────────────────────────────| OIDC (mozilla-django-oidc) |──
#     Only set these when OIDC is actually configured - mozilla-django-oidc will
#   error on startup if the endpoint settings are missing but the app is loaded.

if app_config.oidc_enabled:
    OIDC_RP_CLIENT_ID = app_config.oidc_client_id
    OIDC_RP_CLIENT_SECRET = app_config.oidc_client_secret

    OIDC_OP_AUTHORIZATION_ENDPOINT = (
        f"{app_config.oidc_issuer}/oauth/v2/authorize"
    )
    OIDC_OP_TOKEN_ENDPOINT = f"{app_config.oidc_issuer}/oauth/v2/token"
    OIDC_OP_USER_ENDPOINT = f"{app_config.oidc_issuer}/oidc/v1/userinfo"
    OIDC_OP_JWKS_ENDPOINT = f"{app_config.oidc_issuer}/oauth/v2/keys"
    OIDC_OP_LOGOUT_ENDPOINT = f"{app_config.oidc_issuer}/oidc/v1/end_session"

    OIDC_RP_SIGN_ALGO = "RS256"
    OIDC_USE_PKCE = True
    OIDC_PKCE_CODE_CHALLENGE_METHOD = "S256"
    OIDC_RP_SCOPES = "openid email profile"
    OIDC_STORE_ACCESS_TOKEN = False
    OIDC_STORE_ID_TOKEN = False

# ───────────────────────────────────────────────────────────────────| Email |──
#     See https://docs.djangoproject.com/en/6.0/ref/settings/#default-from-email

DEFAULT_FROM_EMAIL = app_env.default_from_email
EMAIL_BACKEND = (
    "django.core.mail.backends.console.EmailBackend"
    if DEBUG
    else "django.core.mail.backends.smtp.EmailBackend"
)

# ─────────────────────────────────────────────────────────────────| Logging |──
#                See https://docs.djangoproject.com/en/6.0/ref/settings/#logging

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        "django": {"handlers": ["console"], "level": "ERROR"},
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}
