from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    path("login/", views.LoginPageView.as_view(), name="login"),
    path(
        "attributions/", views.AttributionsView.as_view(), name="attributions"
    ),
    path(
        "dashboard/",
        login_required(views.DashboardView.as_view()),
        name="dashboard",
    ),
    path(
        "clients/",
        login_required(views.ClientListView.as_view()),
        name="client-list",
    ),
    path(
        "clients/new/",
        login_required(views.NewClientView.as_view()),
        name="client-new",
    ),
    path(
        "clients/<int:pk>/edit/",
        login_required(views.EditClientView.as_view()),
        name="client-edit",
    ),
    path(
        "clients/<int:pk>/delete/",
        login_required(views.DeleteClientView.as_view()),
        name="client-delete",
    ),
    path(
        "clients/<int:pk>/",
        login_required(views.ClientDetailView.as_view()),
        name="client-detail",
    ),
    path(
        "clients/<int:pk>/retainers/new/",
        login_required(views.NewRetainerView.as_view()),
        name="retainer-new",
    ),
    path(
        "clients/<int:pk>/retainers/<int:retainer_pk>/edit/",
        login_required(views.EditRetainerView.as_view()),
        name="retainer-edit",
    ),
    path(
        "clients/<int:pk>/retainers/<int:retainer_pk>/delete/",
        login_required(views.DeleteRetainerView.as_view()),
        name="retainer-delete",
    ),
    path(
        "clients/<int:pk>/retainers/<int:retainer_pk>/",
        login_required(views.RetainerDetailView.as_view()),
        name="retainer-detail",
    ),
    path(
        "clients/<int:pk>/retainers/<int:retainer_pk>/terms/<int:term_number>/",
        login_required(views.RetainerDetailView.as_view()),
        name="retainer-detail-term",
    ),
    path(
        "clients/<int:pk>/retainers/<int:retainer_pk>/log/",
        login_required(views.LogTimeView.as_view()),
        name="log-time",
    ),
    path(
        "clients/<int:pk>/retainers/<int:retainer_pk>/work-orders/",
        login_required(views.WorkOrderListView.as_view()),
        name="work-order-list",
    ),
    path(
        "clients/<int:pk>/retainers/<int:retainer_pk>/work-orders/new/",
        login_required(views.NewWorkOrderView.as_view()),
        name="work-order-new",
    ),
    path(
        "clients/<int:pk>/retainers/<int:retainer_pk>/work-orders/"
        "<int:wo_pk>/",
        login_required(views.WorkOrderDetailView.as_view()),
        name="work-order-detail",
    ),
    path(
        "clients/<int:pk>/retainers/<int:retainer_pk>/work-orders/"
        "<int:wo_pk>/edit/",
        login_required(views.EditWorkOrderView.as_view()),
        name="work-order-edit",
    ),
    path(
        "clients/<int:pk>/retainers/<int:retainer_pk>/work-orders/"
        "<int:wo_pk>/delete/",
        login_required(views.DeleteWorkOrderView.as_view()),
        name="work-order-delete",
    ),
    path(
        "clients/<int:pk>/retainers/<int:retainer_pk>/work-orders/"
        "<int:wo_pk>/items/<int:item_pk>/start/",
        login_required(views.StartTimerView.as_view()),
        name="timer-start",
    ),
    path(
        "clients/<int:pk>/retainers/<int:retainer_pk>/work-orders/"
        "<int:wo_pk>/items/<int:item_pk>/stop/",
        login_required(views.StopTimerView.as_view()),
        name="timer-stop",
    ),
    path(
        "clients/<int:pk>/retainers/<int:retainer_pk>/work-orders/"
        "<int:wo_pk>/items/<int:item_pk>/confirm-overage/",
        login_required(views.ConfirmOverageView.as_view()),
        name="timer-confirm-overage",
    ),
    path(
        "clients/<int:pk>/retainers/<int:retainer_pk>/work-orders/"
        "<int:wo_pk>/items/<int:item_pk>/status/",
        login_required(views.TimerStatusView.as_view()),
        name="timer-status",
    ),
    path(
        "clients/<int:pk>/retainers/<int:retainer_pk>/work-orders/"
        "<int:wo_pk>/items/<int:item_pk>/complete/",
        login_required(views.CompleteWorkOrderItemView.as_view()),
        name="work-order-item-complete",
    ),
    path(
        "clients/<int:pk>/retainers/<int:retainer_pk>/new-term/",
        login_required(views.NewTermView.as_view()),
        name="new-term",
    ),
    path(
        "clients/<int:pk>/retainers/<int:retainer_pk>/purchase-hours/",
        login_required(views.PurchaseHoursView.as_view()),
        name="purchase-hours",
    ),
    path(
        "clients/<int:pk>/retainers/<int:retainer_pk>/bill-overage/",
        login_required(views.BillOverageView.as_view()),
        name="bill-overage",
    ),
    path(
        "clients/<int:pk>/retainers/<int:retainer_pk>/terms/"
        "<int:term_number>/bill-overage/",
        login_required(views.BillOverageView.as_view()),
        name="bill-overage-term",
    ),
    path(
        "clients/<int:pk>/retainers/<int:retainer_pk>/report/",
        login_required(views.ReportView.as_view()),
        name="report",
    ),
    path(
        "clients/<int:pk>/retainers/<int:retainer_pk>/terms/"
        "<int:term_number>/report/",
        login_required(views.ReportView.as_view()),
        name="report-term",
    ),
    path(
        "clients/<int:pk>/retainers/<int:retainer_pk>/reports/"
        "<int:report_pk>/download/",
        login_required(views.DownloadReportView.as_view()),
        name="report-download",
    ),
    path(
        "time-entries/<int:pk>/delete/",
        login_required(views.DeleteTimeEntryView.as_view()),
        name="delete-time-entry",
    ),
    path(
        "retainers/",
        login_required(views.RetainerListView.as_view()),
        name="retainer-list",
    ),
    path(
        "work-orders/",
        login_required(views.AllWorkOrdersView.as_view()),
        name="work-order-list-all",
    ),
]
