# Generated by Django 6.0.5 on 2026-05-27 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="notes",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ClientTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term_number", models.PositiveIntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("monthly_hours", models.FloatField()),
                (
                    "carry_over_type",
                    models.CharField(
                        choices=[
                            ("NONE", "First term (no carryover)"),
                            (
                                "CONVERT_TO_DEV",
                                "Convert remaining support > development hours (/2)",
                            ),
                            (
                                "MIGRATE_SUPPORT",
                                "Migrate support hours forward (max 6h)",
                            ),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                ("dev_hours_from_conversion", models.FloatField(default=0)),
                ("migrated_support_hours", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="tracker.client",
                    ),
                ),
            ],
            options={
                "ordering": ["term_number"],
                "unique_together": {("client", "term_number")},
            },
        ),
    ]
