# Generated by Django 6.0.5 on 2026-07-11 21:28

import django.core.validators
from django.db import migrations, models


def split_decimal_hours_into_minutes(apps, schema_editor):
    """Splits each record's fractional hours into the new minutes fields.

    Runs after the minutes columns are added but before the hours columns
    are altered to PositiveIntegerField, so the pre-alter float value is
    still available to split accurately (e.g. 1.5 -> 1h 30m instead of
    truncating to 1h).

    Args:
        apps: Historical app registry for this migration state.
        schema_editor: Unused, required by the RunPython signature.
    """

    def split(value):
        whole = int(value)
        minutes = round((value - whole) * 60)
        if minutes == 60:
            whole, minutes = whole + 1, 0
        return whole, minutes

    TimeEntry = apps.get_model("tracker", "TimeEntry")
    ClientTerm = apps.get_model("tracker", "ClientTerm")
    OverageBilling = apps.get_model("tracker", "OverageBilling")

    for entry in TimeEntry.objects.all():
        entry.hours, entry.minutes = split(entry.hours)
        entry.save(update_fields=["hours", "minutes"])

    for term in ClientTerm.objects.all():
        term.monthly_hours, term.monthly_minutes = split(term.monthly_hours)
        term.dev_hours_from_conversion, term.dev_minutes_from_conversion = (
            split(term.dev_hours_from_conversion)
        )
        term.migrated_support_hours, term.migrated_support_minutes = split(
            term.migrated_support_hours
        )
        term.save(
            update_fields=[
                "monthly_hours",
                "monthly_minutes",
                "dev_hours_from_conversion",
                "dev_minutes_from_conversion",
                "migrated_support_hours",
                "migrated_support_minutes",
            ]
        )

    for billing in OverageBilling.objects.all():
        billing.hours_charged, billing.minutes_charged = split(
            billing.hours_charged
        )
        billing.save(update_fields=["hours_charged", "minutes_charged"])


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_overagebilling"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientterm",
            name="dev_minutes_from_conversion",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(59)],
            ),
        ),
        migrations.AddField(
            model_name="clientterm",
            name="migrated_support_minutes",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(59)],
            ),
        ),
        migrations.AddField(
            model_name="clientterm",
            name="monthly_minutes",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(59)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="overagebilling",
            name="minutes_charged",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(59)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timeentry",
            name="minutes",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(59)],
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            split_decimal_hours_into_minutes, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="clientterm",
            name="dev_hours_from_conversion",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="clientterm",
            name="migrated_support_hours",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="clientterm",
            name="monthly_hours",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="overagebilling",
            name="hours_charged",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="hours",
            field=models.PositiveIntegerField(),
        ),
    ]
