# Generated by Django 6.0.5 on 2026-07-12 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_clientterm_dev_minutes_from_conversion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeentry",
            name="term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_entries",
                to="tracker.clientterm",
            ),
        ),
    ]
