# Generated by Django 6.0.5 on 2026-07-13 13:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0009_retainer"),
    ]

    operations = [
        migrations.CreateModel(
            name="HoursPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hours", models.PositiveIntegerField()),
                (
                    "minutes",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(59)
                        ]
                    ),
                ),
                ("invoice_ref", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REFUNDED", "Refunded"),
                            ("CARRIED_FORWARD", "Carried forward"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hours_purchases",
                        to="tracker.clientterm",
                    ),
                ),
            ],
            options={
                "ordering": ["purchased_at"],
            },
        ),
    ]
