# Generated by Django 6.0.5 on 2026-07-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0012_hourspurchase_from_historical_billing"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("logo_url", models.URLField(blank=True)),
                ("address_line1", models.CharField(blank=True, max_length=200)),
                ("address_line2", models.CharField(blank=True, max_length=200)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("vat_number", models.CharField(blank=True, max_length=50)),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=50),
                ),
                ("iban", models.CharField(blank=True, max_length=50)),
                ("bic", models.CharField(blank=True, max_length=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company Profile",
                "verbose_name_plural": "Company Profile",
            },
        ),
    ]
