# Generated by Django 6.0.5 on 2026-07-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0013_companyprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="address_line1",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="client",
            name="address_line2",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="client",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="client",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="client",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
